### ISSUE TITLE
Problem running check on Visual Components

### ISSUE THREAD

**Issue by Nichneo** [SalesforceLabs/OrgCheck#45]
OrgCheck Information
Version: v1.8.3
Navigation Information
Page: /apex/OrgCheck_VisualComponents_VFP

System Information
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/88.0.4324.150 Safari/537.36
Operating System: Win32
Language: es-ES

Error #0: ERROR_HTTP_400
When: While creating a promise to call "private_query".
What:
index: 7
queryMore: false
queryString: SELECT MetadataComponentId, MetadataComponentName, MetadataComponentType, RefMetadataComponentId, RefMetadataComponentName, RefMetadataComponentType FROM MetadataComponentDependency WHERE RefMetadataComponentId IN ('0Ab1t000000oNsA','0Ab1t000000oNsB','0Ab1t000000oP1A','0Ab1t000000oP1B','0Ab1t000000oPOO','0Ab1t000000oPOQ','0Ab1t000000oPOR','0Ab1t000000oPOS','0Ab1t000000oPis','0Ab1t000000oPit','0Ab1t000000oPiu','0Ab1t000000oQPt','0Ab1t000000oREn','0Ab1t000000oREo','0Ab1t000000oREp','0Ab1t000000oREq','0Ab1t000000oREr','0Ab1t000000oREs','0Ab1t000000oREt','0Ab1t000000oREu','0Ab1t000000oREv','0Ab1t000000oRo2','0Ab1t000000oRo3','0Ab1t000000oSsK','0Ab1t000000oSsL','0Ab1t000000oSsM','0Ab1t000000oSsN','0Ab1t000000oSsO','0Ab1t000000oSsP','0Ab1t000000oSsQ','0Ab1t000000oSsR','0Ab1t000000oSsS','0Ab1t000000oSsT','0Ab1t000000oSsU','0Ab1t000000oSsV','0Ab1t000000oSsW','0Ab1t000000oSsX','0Ab1t000000oSsY','0Ab1t000000oSsZ','0Ab1t000000oSsa','0Ab1t000000oSsb','0Ab1t000000oSsc','0Ab1t000000oSsd','0Ab1t000000oSse','0Ab1t000000oSsf','0Ab1t000000oSsg','0Ab1t000000oSsh','0Ab1t000000oSsi','0Ab1t000000oSsj','0Ab1t000000oSsk') OR MetadataComponentId IN ('0Ab1t000000oNsA','0Ab1t000000oNsB','0Ab1t000000oP1A','0Ab1t000000oP1B','0Ab1t000000oPOO','0Ab1t000000oPOQ','0Ab1t000000oPOR','0Ab1t000000oPOS','0Ab1t000000oPis','0Ab1t000000oPit','0Ab1t000000oPiu','0Ab1t000000oQPt','0Ab1t000000oREn','0Ab1t000000oREo','0Ab1t000000oREp','0Ab1t000000oREq','0Ab1t000000oREr','0Ab1t000000oREs','0Ab1t000000oREt','0Ab1t000000oREu','0Ab1t000000oREv','0Ab1t000000oRo2','0Ab1t000000oRo3','0Ab1t000000oSsK','0Ab1t000000oSsL','0Ab1t000000oSsM','0Ab1t000000oSsN','0Ab1t000000oSsO','0Ab1t000000oSsP','0Ab1t000000oSsQ','0Ab1t000000oSsR','0Ab1t000000oSsS','0Ab1t000000oSsT','0Ab1t000000oSsU','0Ab1t000000oSsV','0Ab1t000000oSsW','0Ab1t000000oSsX','0Ab1t000000oSsY','0Ab1t000000oSsZ','0Ab1t000000oSsa','0Ab1t000000oSsb','0Ab1t000000oSsc','0Ab1t000000oSsd','0Ab1t000000oSse','0Ab1t000000oSsf','0Ab1t000000oSsg','0Ab1t000000oSsh','0Ab1t000000oSsi','0Ab1t000000oSsj','0Ab1t000000oSsk')
queryUseTooling: true
ERROR_HTTP_400: Access Declined
   at h.getError (https://lidleu--orgcheck.eu16.visual.force.com/resource/1615532460000/orgcheck__OrgCheck_JSForce_SR:3:6851)
   at https://lidleu--orgcheck.eu16.visual.force.com/resource/1615532460000/orgcheck__OrgCheck_JSForce_SR:3:5201
   at o (https://lidleu--orgcheck.eu16.visual.force.com/resource/1615532460000/orgcheck__OrgCheck_JSForce_SR:8:3810)
   at https://lidleu--orgcheck.eu16.visual.force.com/resource/1615532460000/orgcheck__OrgCheck_JSForce_SR:8:4587
   at MutationObserver.r (https://lidleu--orgcheck.eu16.visual.force.com/resource/1615532460000/orgcheck__OrgCheck_JSForce_SR:4:7059)

**Comment by VinceFINET** [comment]
Thank you for using OrgCheck and share your issue with the community.
I see you are using 1.8 (see in the log "Version: v1.8.3")
I pushed you the last version 1.9.

Do you reproduce the issue with this new version?

**Comment by Nichneo** [comment]
Hi Vince,
yes, this is still happening, here new error:
OrgCheck Information
Version: v1.9.1
Installed on OrgId: 00D58000000K3E6

Navigation Information
Page: /apex/OrgCheck_VisualComponents_VFP

System Information
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/88.0.4324.150 Safari/537.36
Operating System: Win32
Language: es-ES

Error #0: ERROR_HTTP_400
When: While creating a promise to call "private_query".
What:
index: 4
queryMore: false
queryString: SELECT MetadataComponentId, MetadataComponentName, MetadataComponentType, RefMetadataComponentId, RefMetadataComponentName, RefMetadataComponentType FROM MetadataComponentDependency WHERE RefMetadataComponentId IN ('0Ab1t000000CCP1','0Ab1t000000CEZD','0Ab1t000000CEZE','0Ab1t000000CEZF','0Ab1t000000CEZG','0Ab1t000000CEZH','0Ab1t000000CEZI','0Ab1t000000CEZJ','0Ab1t000000CEZK','0Ab1t000000CEZL','0Ab1t000000CEZM','0Ab1t000000Jfcg','0Ab1t000000Jfch','0Ab1t000000Jfci','0Ab1t000000Jfcj','0Ab1t000000Jfck','0Ab1t000000Jfcl','0Ab1t000000KB76','0Ab1t000000KB7A','0Ab1t000000KB7B','0Ab1t000000KB7C','0Ab1t000000KB7E','0Ab1t000000KB7F','0Ab1t000000KB7G','0Ab1t000000KB7I','0Ab1t000000KB7L','0Ab1t000000KB7M','0Ab1t000000KB7N','0Ab1t000000KB7O','0Ab1t000000KB7R','0Ab1t000000KUc5','0Ab1t000000KUc6','0Ab1t000000Sni9','0Ab1t000000SniA','0Ab1t000000SniB','0Ab1t000000SniC','0Ab1t000000SniD','0Ab1t000000SrHY','0Ab1t000000SrHZ','0Ab1t000000SrHa','0Ab1t000000SrHb','0Ab1t000000SrHc','0Ab1t000000SrHd','0Ab1t000000SrHe','0Ab1t000000SrHf','0Ab1t000000SrHg','0Ab1t000000SrHh','0Ab1t000000SrHi','0Ab1t000000SrHj','0Ab1t000000SrHk') OR MetadataComponentId IN ('0Ab1t000000CCP1','0Ab1t000000CEZD','0Ab1t000000CEZE','0Ab1t000000CEZF','0Ab1t000000CEZG','0Ab1t000000CEZH','0Ab1t000000CEZI','0Ab1t000000CEZJ','0Ab1t000000CEZK','0Ab1t000000CEZL','0Ab1t000000CEZM','0Ab1t000000Jfcg','0Ab1t000000Jfch','0Ab1t000000Jfci','0Ab1t000000Jfcj','0Ab1t000000Jfck','0Ab1t000000Jfcl','0Ab1t000000KB76','0Ab1t000000KB7A','0Ab1t000000KB7B','0Ab1t000000KB7C','0Ab1t000000KB7E','0Ab1t000000KB7F','0Ab1t000000KB7G','0Ab1t000000KB7I','0Ab1t000000KB7L','0Ab1t000000KB7M','0Ab1t000000KB7N','0Ab1t000000KB7O','0Ab1t000000KB7R','0Ab1t000000KUc5','0Ab1t000000KUc6','0Ab1t000000Sni9','0Ab1t000000SniA','0Ab1t000000SniB','0Ab1t000000SniC','0Ab1t000000SniD','0Ab1t000000SrHY','0Ab1t000000SrHZ','0Ab1t000000SrHa','0Ab1t000000SrHb','0Ab1t000000SrHc','0Ab1t000000SrHd','0Ab1t000000SrHe','0Ab1t000000SrHf','0Ab1t000000SrHg','0Ab1t000000SrHh','0Ab1t000000SrHi','0Ab1t000000SrHj','0Ab1t000000SrHk')
queryUseTooling: true
ERROR_HTTP_400: Access Declined
   at h.getError (https://lidleu--orgcheck.eu16.visual.force.com/resource/1615532460000/orgcheck__OrgCheck_JSForce_SR:3:6851)
   at https://lidleu--orgcheck.eu16.visual.force.com/resource/1615532460000/orgcheck__OrgCheck_JSForce_SR:3:5201
   at o (https://lidleu--orgcheck.eu16.visual.force.com/resource/1615532460000/orgcheck__OrgCheck_JSForce_SR:8:3810)
   at https://lidleu--orgcheck.eu16.visual.force.com/resource/1615532460000/orgcheck__OrgCheck_JSForce_SR:8:4587
   at MutationObserver.r (https://lidleu--orgcheck.eu16.visual.force.com/resource/1615532460000/orgcheck__OrgCheck_JSForce_SR:4:7059)

**Comment by VinceFINET** [comment]
It looks like a token issue, maybe like here https://developer.salesforce.com/forums/?id=9060G0000005UztQAE

is it still the same issue after closing the browser, clean cache et relogging again?

**Comment by Nichneo** [comment]
Hi @VinceFINET, unfortunately yes, I've cleaned Chrome cache, close the browser, and tried again but same issue.

**Comment by VinceFINET** [comment]
ERROR_HTTP_400: Access Declined --> also in #44

**Comment by VinceFINET** [comment]
Duplicate of #74
