### ISSUE TITLE
Oxygen: Page-Layouts throws error

### ISSUE THREAD

**Issue by grantlavers** [SalesforceLabs/OrgCheck#609]
Trying to view information about Page Layouts in Data Model tab
Error thrown:
Run recipe "page-layouts" An error occurred while running the dataset page-layouts.
Run dataset "page-layouts" There was an error during the process...
Context information about the issue:
Message: There was an error while calling Composite Tooling API to get metadata at scale.
Type: Layout
AllIds: ["]
ByPasses: FIELD_INTEGRITY_EXCEPTION, UNKNOWN_EXCEPTION
HttpStatusCode: 400
HttpResponse: [{"message":"insufficient access rights on cross-reference id","errorCode":"INSUFFICIENT_ACCESS"}]
Where: SalesforceManagerImpl.readMetadataAtScale

**Comment by VinceFINET** [comment]
Assign your user to the permission set from the package called Org Check
users.

And tell me if it is working better.

Thank you

Le mer. 17 déc. 2025 à 22:22, Grant Lavers ***@***.***> a
écrit :

**Comment by grantlavers** [comment]
Assigned Permission Set to user.
Logged out and back in again to ensure applied

Same error:
***@***.***

<img width="1078" height="484" alt="Image" src="https://github.com/user-attachments/assets/7cb4bcd7-efe1-46b4-9e02-35c106a00baa" />

P PLEASE CONSIDER THE ENVIRONMENT BEFORE YOU PRINT THIS E-MAIL

**Comment by VinceFINET** [comment]
oh my... i just figure out that in your initial message that specific part:
`AllIds: ["]`

I am on lead !

**Comment by VinceFINET** [comment]
dear @grantlavers 

could you check the FAQ specially question 6 at https://salesforcelabs.github.io/OrgCheck/faq/

<img width="787" height="323" alt="Image" src="https://github.com/user-attachments/assets/fd9511a8-ac4d-460b-843f-913478a9c73f" />

**Comment by grantlavers** [comment]
Vincent,

Unable to access FAQ due to 404 error.
Image however ok, but no resolution.
***@***.***


***@***.***

Have deselected all options and no change in functionality
***@***.***

Grant Lavers
Data Analyst - Salesforce
Email: ***@***.***
Phone: 4935 1430
Mobile: 0417160083
NEW LAMBTON NSW 2305
The Wests Group Australia
NEW LAMBTON NSW 2305


The Wests Group Australia acknowledges the traditional owners and custodians of the lands within our organisational footprint: Awabakal, Worimi, Darkinjung, Geawegal, and Wonnarua Nations. We pay our respects to Elders past, present and emerging.

This email is intended only to be read or used by the addressee. The information contained in this e-mail message may be confidential information. If you are not the intended recipient, any use, interference with, distribution, disclosure or copying of this material is unauthorised and prohibited. Confidentiality attached to this communication is not waived or lost by reason of the mistaken delivery to you. If you have received this message in error, please delete it and notify us by return e-mail or telephone The Wests Group Australia on +61 2 49351300 
P PLEASE CONSIDER THE ENVIRONMENT BEFORE YOU PRINT THIS E-MAIL

**Comment by VinceFINET** [comment]
I published a new version called 7.4 this morning.
I you can check if this resolves your issue.
If not if you agree we can have screenshare for me to better understand what's going on in your case. (let's plan this via email or trailblazer community private message)

**Comment by grantlavers** [comment]
Updated the installed version in my sandbox and the issue persists.

Happy to do screenshare, but if not in next 2 days then will have to be in new year.
***@***.***


Grant Lavers
Data Analyst - Salesforce
Email: ***@***.***
Phone: 4935 1430
Mobile: 0417160083
NEW LAMBTON NSW 2305
The Wests Group Australia
NEW LAMBTON NSW 2305


The Wests Group Australia acknowledges the traditional owners and custodians of the lands within our organisational footprint: Awabakal, Worimi, Darkinjung, Geawegal, and Wonnarua Nations. We pay our respects to Elders past, present and emerging.

This email is intended only to be read or used by the addressee. The information contained in this e-mail message may be confidential information. If you are not the intended recipient, any use, interference with, distribution, disclosure or copying of this material is unauthorised and prohibited. Confidentiality attached to this communication is not waived or lost by reason of the mistaken delivery to you. If you have received this message in error, please delete it and notify us by return e-mail or telephone The Wests Group Australia on +61 2 49351300 
P PLEASE CONSIDER THE ENVIRONMENT BEFORE YOU PRINT THIS E-MAIL

**Comment by VinceFINET** [comment]
Let's connect directly (in private) in parallel of this thread for this issue to be solved asap! :D

**Comment by VinceFINET** [comment]
i have the same issue in another org, it's a limitation of salesforce in the flow i am using.
so i will just add the bypass the error code "INSUFFICIENT_ACCESS" but only with the message "insufficient access rights on cross-reference id"

need to do this as well in oxygen.

**Comment by lsaggu** [comment]
Hello! I am experiencing this issue as well. I have assigned my user the permission set specified here, and our org does not have any raised Session Security Level Policies.

It looks like you're actively working on this, so I'll just keep an eye on this thread. If you could use additional information from me to help with this, please let me know.

**Comment by VinceFINET** [comment]
That bug will be fixed when I release Oxygen.
